api:
  dashboard: true
  insecure: true          # dev only

log:
  level: INFO

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
    network: hermes-network
  file:
    directory: /etc/traefik/dynamic
    watch: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
